[package]
name = "eudplib-epscript"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
pyo3 = { version = "0.25.1", features = ["abi3"] }
regex = { version = "1.11.1", features = [] }
