[package]
name = "eudplib_core_allocator"
version = "0.1.0"
edition = "2021"

[lib]
name = "allocator"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
