name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unittest:
    name: Unittest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run unit test
      run: |
        python setup.py install
        cd tests
        python test_unittest.py
        cd ..

  mypy:
    name: mypy
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy for Python 3.11
        run: mypy eudplib --python-version 3.11
      - name: Run mypy for Python 3.10
        run: mypy eudplib --python-version 3.10

  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@v1.0.4
        with:
          config: ./.typos.toml
